# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-14 14:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Price', models.DecimalField(decimal_places=2, max_digits=9)),
                ('Date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='EventTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Descrition', models.TextField(blank=True, max_length=50, null=True)),
                ('Category', models.CharField(blank=True, max_length=50, null=True)),
                ('tags', models.ManyToManyField(to='tags.Tag')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='id_event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EventApp.EventTemplate'),
        ),
    ]
