# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-28 05:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ShortName', models.CharField(blank=True, max_length=20, null=True)),
                ('Last_name', models.CharField(blank=True, max_length=30, null=True)),
                ('First_name', models.CharField(blank=True, max_length=30, null=True)),
                ('Second_name', models.CharField(blank=True, max_length=30, null=True)),
                ('Birthdate', models.DateField(blank=True, null=True)),
                ('Phone', models.CharField(blank=True, max_length=15, null=True)),
                ('Email', models.EmailField(blank=True, max_length=254, null=True)),
                ('Site', models.CharField(blank=True, max_length=50, null=True)),
                ('Social_status', models.CharField(choices=[('1', 'Школьник'), ('2', 'Студент'), ('3', 'Работающий'), ('4', 'Безработный'), ('0', 'Неизвестно')], default='0', max_length=2)),
                ('Sex', models.CharField(choices=[('1', 'муж'), ('0', 'жен')], default='1', max_length=2)),
            ],
        ),
    ]
