# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-27 05:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0001_initial'),
        ('ClientApp', '0002_achievment'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievment',
            name='tags',
            field=models.ManyToManyField(to='tags.Tag'),
        ),
        migrations.AddField(
            model_name='client',
            name='tags',
            field=models.ManyToManyField(to='tags.Tag'),
        ),
    ]
