# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-21 12:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClientApp', '0004_client_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='First_name',
        ),
        migrations.RemoveField(
            model_name='client',
            name='Last_name',
        ),
        migrations.RemoveField(
            model_name='client',
            name='Second_name',
        ),
        migrations.AlterField(
            model_name='client',
            name='Phone',
            field=models.CharField(blank=True, default='', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='ShortName',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='Site',
            field=models.URLField(default=''),
        ),
        migrations.AlterField(
            model_name='client',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, to='tags.Tag'),
        ),
    ]
