# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-27 08:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClientApp', '0005_auto_20180521_2126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='ShortName',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='Site',
            field=models.URLField(blank=True, default='https://vk.com', null=True),
        ),
    ]
