# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-27 05:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ClientApp', '0003_auto_20180427_1410'),
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Good',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Description', models.TextField()),
                ('Notes', models.TextField(blank=True, null=True)),
                ('Price', models.DecimalField(decimal_places=2, max_digits=9)),
                ('Category', models.CharField(choices=[('1', 'Настольные игры'), ('2', 'Коллекционные карточные игры'), ('3', 'Варгейм')], default='1', max_length=2)),
                ('FreeAmount', models.IntegerField(default=0)),
                ('HoldAmountBuy', models.IntegerField(default=0)),
                ('HoldAmountSale', models.IntegerField(default=0)),
                ('tags', models.ManyToManyField(to='tags.Tag')),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField()),
                ('DateFin', models.DateField(blank=True, null=True)),
                ('Note', models.CharField(blank=True, max_length=50, null=True)),
                ('Status', models.CharField(choices=[('1', 'Завершен'), ('2', 'В процессе'), ('3', 'Отменен')], default='1', max_length=2)),
                ('id_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ClientApp.Client')),
                ('id_manager', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('id_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ShopApp.Good')),
                ('tags', models.ManyToManyField(to='tags.Tag')),
            ],
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField()),
                ('Note', models.CharField(blank=True, max_length=50, null=True)),
                ('id_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ClientApp.Client')),
                ('id_manager', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
